[Export]
baked_state = false
offer_binder = true
slider_server_url="https://computationalthinking-sliderserver-droplet.plutojl.org"
ignore_cache = [
    "index.jl",
]
create_index = false

[SliderServer]
exclude=[
    # these are in the repo but not used on the website
    "../notebooks/color_transfer_ds.jl",
]
